// <auto-generated />
using BlazorServer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BlazorServer.Data.Migrations
{
    [DbContext(typeof(AppDBContext))]
    partial class AppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0-preview.6.21352.1");

            modelBuilder.Entity("BlazorServer.Data.Models.Post", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("PostId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            PostId = 1,
                            Content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer pretium libero eget risus gravida eleifend. Morbi sit amet lacus ligula. Donec pharetra, nisi vitae consequat consequat, est massa tincidunt odio, non dapibus risus massa sit amet enim. Sed scelerisque eget nisl in mattis. Morbi posuere, massa vel pretium ornare, est elit posuere massa, a consectetur leo lacus ut erat. Duis eu imperdiet ipsum. Nulla facilisi. Maecenas nunc dolor, egestas nec nunc eu, tempus placerat purus. Phasellus eget purus augue. Praesent vel erat accumsan, pretium orci at, pharetra augue. Vivamus sagittis consequat lectus eu maximus. Vestibulum vitae arcu enim. Vestibulum finibus at quam in faucibus. Morbi maximus cursus scelerisque.",
                            Title = "Post 1"
                        },
                        new
                        {
                            PostId = 2,
                            Content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer pretium libero eget risus gravida eleifend. Morbi sit amet lacus ligula. Donec pharetra, nisi vitae consequat consequat, est massa tincidunt odio, non dapibus risus massa sit amet enim. Sed scelerisque eget nisl in mattis. Morbi posuere, massa vel pretium ornare, est elit posuere massa, a consectetur leo lacus ut erat. Duis eu imperdiet ipsum. Nulla facilisi. Maecenas nunc dolor, egestas nec nunc eu, tempus placerat purus. Phasellus eget purus augue. Praesent vel erat accumsan, pretium orci at, pharetra augue. Vivamus sagittis consequat lectus eu maximus. Vestibulum vitae arcu enim. Vestibulum finibus at quam in faucibus. Morbi maximus cursus scelerisque.",
                            Title = "Post 2"
                        },
                        new
                        {
                            PostId = 3,
                            Content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer pretium libero eget risus gravida eleifend. Morbi sit amet lacus ligula. Donec pharetra, nisi vitae consequat consequat, est massa tincidunt odio, non dapibus risus massa sit amet enim. Sed scelerisque eget nisl in mattis. Morbi posuere, massa vel pretium ornare, est elit posuere massa, a consectetur leo lacus ut erat. Duis eu imperdiet ipsum. Nulla facilisi. Maecenas nunc dolor, egestas nec nunc eu, tempus placerat purus. Phasellus eget purus augue. Praesent vel erat accumsan, pretium orci at, pharetra augue. Vivamus sagittis consequat lectus eu maximus. Vestibulum vitae arcu enim. Vestibulum finibus at quam in faucibus. Morbi maximus cursus scelerisque.",
                            Title = "Post 3"
                        },
                        new
                        {
                            PostId = 4,
                            Content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer pretium libero eget risus gravida eleifend. Morbi sit amet lacus ligula. Donec pharetra, nisi vitae consequat consequat, est massa tincidunt odio, non dapibus risus massa sit amet enim. Sed scelerisque eget nisl in mattis. Morbi posuere, massa vel pretium ornare, est elit posuere massa, a consectetur leo lacus ut erat. Duis eu imperdiet ipsum. Nulla facilisi. Maecenas nunc dolor, egestas nec nunc eu, tempus placerat purus. Phasellus eget purus augue. Praesent vel erat accumsan, pretium orci at, pharetra augue. Vivamus sagittis consequat lectus eu maximus. Vestibulum vitae arcu enim. Vestibulum finibus at quam in faucibus. Morbi maximus cursus scelerisque.",
                            Title = "Post 4"
                        },
                        new
                        {
                            PostId = 5,
                            Content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer pretium libero eget risus gravida eleifend. Morbi sit amet lacus ligula. Donec pharetra, nisi vitae consequat consequat, est massa tincidunt odio, non dapibus risus massa sit amet enim. Sed scelerisque eget nisl in mattis. Morbi posuere, massa vel pretium ornare, est elit posuere massa, a consectetur leo lacus ut erat. Duis eu imperdiet ipsum. Nulla facilisi. Maecenas nunc dolor, egestas nec nunc eu, tempus placerat purus. Phasellus eget purus augue. Praesent vel erat accumsan, pretium orci at, pharetra augue. Vivamus sagittis consequat lectus eu maximus. Vestibulum vitae arcu enim. Vestibulum finibus at quam in faucibus. Morbi maximus cursus scelerisque.",
                            Title = "Post 5"
                        },
                        new
                        {
                            PostId = 6,
                            Content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer pretium libero eget risus gravida eleifend. Morbi sit amet lacus ligula. Donec pharetra, nisi vitae consequat consequat, est massa tincidunt odio, non dapibus risus massa sit amet enim. Sed scelerisque eget nisl in mattis. Morbi posuere, massa vel pretium ornare, est elit posuere massa, a consectetur leo lacus ut erat. Duis eu imperdiet ipsum. Nulla facilisi. Maecenas nunc dolor, egestas nec nunc eu, tempus placerat purus. Phasellus eget purus augue. Praesent vel erat accumsan, pretium orci at, pharetra augue. Vivamus sagittis consequat lectus eu maximus. Vestibulum vitae arcu enim. Vestibulum finibus at quam in faucibus. Morbi maximus cursus scelerisque.",
                            Title = "Post 6"
                        },
                        new
                        {
                            PostId = 7,
                            Content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer pretium libero eget risus gravida eleifend. Morbi sit amet lacus ligula. Donec pharetra, nisi vitae consequat consequat, est massa tincidunt odio, non dapibus risus massa sit amet enim. Sed scelerisque eget nisl in mattis. Morbi posuere, massa vel pretium ornare, est elit posuere massa, a consectetur leo lacus ut erat. Duis eu imperdiet ipsum. Nulla facilisi. Maecenas nunc dolor, egestas nec nunc eu, tempus placerat purus. Phasellus eget purus augue. Praesent vel erat accumsan, pretium orci at, pharetra augue. Vivamus sagittis consequat lectus eu maximus. Vestibulum vitae arcu enim. Vestibulum finibus at quam in faucibus. Morbi maximus cursus scelerisque.",
                            Title = "Post 7"
                        },
                        new
                        {
                            PostId = 8,
                            Content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer pretium libero eget risus gravida eleifend. Morbi sit amet lacus ligula. Donec pharetra, nisi vitae consequat consequat, est massa tincidunt odio, non dapibus risus massa sit amet enim. Sed scelerisque eget nisl in mattis. Morbi posuere, massa vel pretium ornare, est elit posuere massa, a consectetur leo lacus ut erat. Duis eu imperdiet ipsum. Nulla facilisi. Maecenas nunc dolor, egestas nec nunc eu, tempus placerat purus. Phasellus eget purus augue. Praesent vel erat accumsan, pretium orci at, pharetra augue. Vivamus sagittis consequat lectus eu maximus. Vestibulum vitae arcu enim. Vestibulum finibus at quam in faucibus. Morbi maximus cursus scelerisque.",
                            Title = "Post 8"
                        },
                        new
                        {
                            PostId = 9,
                            Content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer pretium libero eget risus gravida eleifend. Morbi sit amet lacus ligula. Donec pharetra, nisi vitae consequat consequat, est massa tincidunt odio, non dapibus risus massa sit amet enim. Sed scelerisque eget nisl in mattis. Morbi posuere, massa vel pretium ornare, est elit posuere massa, a consectetur leo lacus ut erat. Duis eu imperdiet ipsum. Nulla facilisi. Maecenas nunc dolor, egestas nec nunc eu, tempus placerat purus. Phasellus eget purus augue. Praesent vel erat accumsan, pretium orci at, pharetra augue. Vivamus sagittis consequat lectus eu maximus. Vestibulum vitae arcu enim. Vestibulum finibus at quam in faucibus. Morbi maximus cursus scelerisque.",
                            Title = "Post 9"
                        },
                        new
                        {
                            PostId = 10,
                            Content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer pretium libero eget risus gravida eleifend. Morbi sit amet lacus ligula. Donec pharetra, nisi vitae consequat consequat, est massa tincidunt odio, non dapibus risus massa sit amet enim. Sed scelerisque eget nisl in mattis. Morbi posuere, massa vel pretium ornare, est elit posuere massa, a consectetur leo lacus ut erat. Duis eu imperdiet ipsum. Nulla facilisi. Maecenas nunc dolor, egestas nec nunc eu, tempus placerat purus. Phasellus eget purus augue. Praesent vel erat accumsan, pretium orci at, pharetra augue. Vivamus sagittis consequat lectus eu maximus. Vestibulum vitae arcu enim. Vestibulum finibus at quam in faucibus. Morbi maximus cursus scelerisque.",
                            Title = "Post 10"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
